name: 'Setup Environment'
description: 'Sets up Node.js and Python environments'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
        cache-dependency-path: package.json

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
