/**
 * Data used in the server tests.
 */

exports =
{
    gTestPokemon:
    {
        "personality": 959407730,
        "otId": 1468790980,
        "nickname": "Venusaur",
        "language": "LANGUAGE_ENGLISH",
        "otName": "Skeli",
        "markings": [false, false, false, false, false, false, false, false],
        "species": "SPECIES_VENUSAUR",
        "item": "ITEM_NONE",
        "experience": 1059860,
        "ppBonuses": [0, 0, 0, 0],
        "friendship": 50,
        "pokeBall": "BALL_TYPE_POKE_BALL",
        "moves": ["MOVE_SYNTHESIS", "MOVE_SLUDGEBOMB", "MOVE_DOUBLEEDGE", "MOVE_SOLARBEAM"],
        "pokerus": 0,
        "metLocaton": 88,
        "ivs": [31, 31, 31, 31, 31, 31],
        "evs": [0, 0, 0, 0, 0, 0],
        "isEgg": false,
        "hiddenAbility": false,
        "gigantamax": false,
        "shiny": false,
        "abilitySlot": 0,
        "gender": "M",
        "level": 100,
        "nature": "NATURE_BOLD",
        "natureMint": 7,
        "metLevel": 100,
        "metGame": "unbound",
        "otGender": "M",
        "rawStats": [301, 180, 222, 196, 236, 236],
        "checksum": "07ce0f2b5455508a03ac9aee947b2760"
    },

    gTestPokemonStringified: `{"abilitySlot": 0, "checksum": "07ce0f2b5455508a03ac9aee947b2760", "evs": [0, 0, 0, 0, 0, 0], "experience": 1059860, "friendship": 50, "gender": "M", "gigantamax": false, "hiddenAbility": false, "isEgg": false, "item": "ITEM_NONE", "ivs": [31, 31, 31, 31, 31, 31], "language": "LANGUAGE_ENGLISH", "level": 100, "markings": [false, false, false, false, false, false, false, false], "metGame": "unbound", "metLevel": 100, "metLocaton": 88, "moves": ["MOVE_SYNTHESIS", "MOVE_SLUDGEBOMB", "MOVE_DOUBLEEDGE", "MOVE_SOLARBEAM"], "nature": "NATURE_BOLD", "natureMint": 7, "nickname": "Venusaur", "otGender": "M", "otId": 1468790980, "otName": "Skeli", "personality": 959407730, "pokeBall": "BALL_TYPE_POKE_BALL", "pokerus": 0, "ppBonuses": [0, 0, 0, 0], "rawStats": [301, 180, 222, 196, 236, 236], "shiny": false, "species": "SPECIES_VENUSAUR"}`,

    gTestPokemon2:
    {
        "personality": 1795261360,
        "otId": 1468790980,
        "nickname": "Gengar",
        "language": "LANGUAGE_ENGLISH",
        "otName": "Skeli",
        "markings": [false, false, false, false, false, false, false, false],
        "species": "SPECIES_GENGAR",
        "item": "ITEM_WIDE_LENS",
        "experience": 621932,
        "ppBonuses": [0, 0, 0, 0],
        "friendship": 255,
        "pokeBall": "BALL_TYPE_PREMIER_BALL",
        "moves": ["MOVE_SHADOWBALL", "MOVE_SLUDGEWAVE", "MOVE_PROTECT", "MOVE_HYPNOSIS"],
        "pokerus": 0,
        "metLocaton": 88,
        "ivs": [31, 0, 31, 31, 31, 31],
        "evs": [2, 0, 4, 252, 252, 0],
        "isEgg": false,
        "hiddenAbility": false,
        "shiny": false,
        "abilitySlot": 0,
        "gender": "M",
        "level": 84,
        "nature": "NATURE_TIMID",
        "metLevel": 10,
        "metGame": "unbound",
        "gigantamax": true,
        "otGender": "M",
        "checksum": "d67026ff547c52fb2a5be981dafa6e89"
    },

    gTestTradeNormalPokemon:
    {
        "personality": 340287010,
        "otId": 2545372516,
        "nickname": "Kadabra",
        "language": "LANGUAGE_ENGLISH",
        "otName": "Karen",
        "markings": [false, false, false, false, false, false, false, false],
        "species": "SPECIES_KADABRA",
        "item": "ITEM_ALAKAZITE",
        "experience": 1059860,
        "ppBonuses": [0, 0, 0, 0],
        "friendship": 54,
        "pokeBall": "BALL_TYPE_ULTRA_BALL",
        "moves": ["MOVE_ENERGYBALL", "MOVE_TAUNT", "MOVE_PSYSHOCK", "MOVE_CHARGEBEAM"],
        "pokerus": 0,
        "metLocaton": 128,
        "ivs": [31, 0, 31, 31, 31, 31],
        "evs": [0, 0, 0, 252, 252, 6],
        "isEgg": false,
        "hiddenAbility": true,
        "shiny": false,
        "abilitySlot": 2,
        "gender": "F",
        "nature": "NATURE_TIMID",
        "metLevel": 50,
        "metGame": "unbound",
        "gigantamax": false,
        "otGender": "F",
        "checksum": "8a7c6770de253562ea2b1459667c2e1b",
    },

    gTestTradeItemPokemon:
    {
        "personality": 1125251413,
        "otId": 1442633000,
        "nickname": "Scyther",
        "language": "LANGUAGE_ENGLISH",
        "otName": "Deneb",
        "markings": [false, false, false, false, false, false, false, false],
        "species": "SPECIES_SCYTHER",
        "item": "ITEM_METAL_COAT",
        "experience": 1000000,
        "ppBonuses": [0, 0, 0, 0],
        "friendship": 255,
        "pokeBall": "BALL_TYPE_ULTRA_BALL",
        "moves": ["MOVE_DUALWINGBEAT", "MOVE_UTURN", "MOVE_KNOCKOFF", "MOVE_SWORDSDANCE"],
        "pokerus": 51,
        "metLocaton": 183,
        "ivs": [31, 31, 31, 31, 0, 31],
        "evs": [0, 252, 0, 252, 0, 6],
        "isEgg": false,
        "hiddenAbility": false,
        "shiny": false,
        "abilitySlot": 1,
        "gender": "F",
        "nature": "NATURE_JOLLY",
        "metLevel": 51,
        "metGame": "unbound",
        "gigantamax": false,
        "otGender": "M",
        "checksum": "25bd4f7cef19c04feda7b7b616a6fbd1",
    },

    gTestTradeShelmet:
    {
        "personality": 118591235,
        "otId": 1442633000,
        "nickname": "Shelmet",
        "language": "LANGUAGE_ENGLISH",
        "otName": "Deneb",
        "markings": [false, false, false, false, false, false, false, false],
        "species": "SPECIES_SHELMET",
        "item": "ITEM_NONE",
        "experience": 1000000,
        "ppBonuses": [0, 0, 0, 0],
        "friendship": 255,
        "pokeBall": "BALL_TYPE_PREMIER_BALL",
        "moves": ["MOVE_BIDE", "MOVE_LEECHLIFE", "MOVE_PROTECT", "MOVE_NONE"],
        "pokerus": 0,
        "metLocaton": 134,
        "ivs": [31, 0, 31, 31, 31, 31],
        "evs": [252, 0, 0, 252, 0, 6],
        "isEgg": false,
        "hiddenAbility": false,
        "shiny": false,
        "abilitySlot": 1,
        "gender": "F",
        "nature": "NATURE_TIMID",
        "metLevel": 0,
        "metGame": "unbound",
        "gigantamax": false,
        "otGender": "M",
        "checksum": "8d612b3bfd6c2617432c755d84d36be5"
    },

    gTestTradeKarrablast:
    {
        "personality": 118591235,
        "otId": 1442633000,
        "nickname": "Knight",
        "language": "LANGUAGE_ENGLISH",
        "otName": "Deneb",
        "markings": [false, false, false, false, false, false, false, false],
        "species": "SPECIES_KARRABLAST",
        "item": "ITEM_NONE",
        "experience": 1000000,
        "ppBonuses": [0, 0, 0, 0],
        "friendship": 255,
        "pokeBall": "BALL_TYPE_PREMIER_BALL",
        "moves": ["MOVE_BIDE", "MOVE_LEECHLIFE", "MOVE_PROTECT", "MOVE_NONE"],
        "pokerus": 0,
        "metLocaton": 134,
        "ivs": [31, 0, 31, 31, 31, 31],
        "evs": [252, 0, 0, 252, 0, 6],
        "isEgg": false,
        "hiddenAbility": false,
        "shiny": false,
        "abilitySlot": 1,
        "gender": "F",
        "nature": "NATURE_TIMID",
        "metLevel": 0,
        "metGame": "unbound",
        "gigantamax": false,
        "otGender": "M",
        "checksum": "b9383393e2e3e868cad54b22abc28ce3"
    },

    gTestBlankPokemon:
    {
        "personality":0,
        "otId":0,
        "nickname":"",
        "language":"",
        "otName":"",
        "markings":null,
        "species":"",
        "item":"",
        "experience":0,
        "ppBonuses":null,
        "friendship":0,
        "pokeBall":"",
        "moves":null,
        "pokerus":0,
        "metLocaton":0,
        "ivs":null,
        "evs":null,
        "isEgg":null,
        "hiddenAbility":null,
        "shiny":null,
        "abilitySlot":0,
        "gender":"",
        "level":0,
        "nature":"",
        "metLevel":0,
        "metGame":"",
        "gigantamax":null,
        "otGender":"",
        "checksum":""
    }
}

module.exports = exports;
