name: Back-End Tests

# Run when pushing to a side branch or manually triggered/called
on:
  push:
    branches-ignore: ["main"] # On main it's run as part of the release pipeline
    paths:
      - ".github/workflows/backend_tests.yml"
      - "server/**"
      - "*requirements.txt"
  workflow_dispatch:
  workflow_call:
    inputs:
      APPDATA:
        required: true
        type: string
      UNBOUND_EMAIL:
        required: true
        type: string
    secrets:
      UNBOUND_EMAIL_PASSWORD:
        required: true
      WONDER_TRADE_WEBHOOK:
        required: true
      ENCRYPTION_KEY:
        required: true
      CHECKSUM_KEY:
        required: true

# Only allow one job to run at a time per branch for direct triggers (PRs, manual), not for workflow calls
concurrency:
  group: ${{ (github.event_name == 'workflow_call' && format('{0}-{1}-{2}', github.workflow, github.ref, github.run_id)) || format('{0}-{1}', github.workflow, github.ref) }}
  cancel-in-progress: true

env:
  # Use inputs when available, otherwise fall back to repository variables/secrets
  APPDATA: ${{ inputs.APPDATA || vars.APPDATA }}
  UNBOUND_EMAIL: ${{ inputs.UNBOUND_EMAIL || vars.UNBOUND_EMAIL }}
  UNBOUND_EMAIL_PASSWORD: ${{ secrets.UNBOUND_EMAIL_PASSWORD }}
  WONDER_TRADE_WEBHOOK: ${{ secrets.WONDER_TRADE_WEBHOOK }}
  ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
  CHECKSUM_KEY: ${{ secrets.CHECKSUM_KEY }}

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      ## Setup dependencies ##
      - name: Setup Node.js with Yarn caching
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: yarn
          cache-dependency-path: server/package.json

      - name: Install dependencies
        run: cd server && yarn install

      ## Tests ##
      - name: Run tests
        run: cd server && yarn test-js

  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      ## Setup dependencies ##
      - name: Setup Python with pip caching
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: |
            requirements.txt
            test-requirements.txt

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r test-requirements.txt --upgrade

      ## Tests ##
      - name: Run tests
        run: cd server && yarn test-py
