name: End-to-End Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DISPLAY: :99
      RESOLUTION: 1920x1080
      APPDATA: ${{ vars.APPDATA }}
      UNBOUND_EMAIL: ${{ vars.UNBOUND_EMAIL }}
      UNBOUND_EMAIL_PASSWORD: ${{ secrets.UNBOUND_EMAIL_PASSWORD }}
      WONDER_TRADE_WEBHOOK: ${{ secrets.WONDER_TRADE_WEBHOOK }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22.x"
        cache: 'yarn'

    - name: Install JS dependencies
      run: (yarn install & yarn --cwd server install & wait)

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r test-requirements.txt

    - name: Install Xvfb & ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb ffmpeg

    - name: Start Website & Server
      run: |
        yarn start &
        yarn --cwd server start &
        sleep 5

    - name: Start Xvfb
      run: |
        Xvfb ${DISPLAY} -screen 0 ${RESOLUTION}x24 &
        sleep 3

    - name: Start recording
      run: |
        # record at 15fps, h264, movflags for faststart
        ffmpeg -probesize 10M -y -f x11grab -r 15 -s ${RESOLUTION} -i ${DISPLAY} \
          -c:v libx264 -preset ultrafast -movflags +faststart video.mp4 &
        echo $! > ffmpeg.pid

    - name: Run Selenium tests
      run: yarn test-selenium
      timeout-minutes: 1 # 1 minute timeout for tests

    - name: Stop recording
      if: always()
      run: |
        # send SIGINT (equivalent to Ctrl-C) so ffmpeg writes its trailer
        kill -SIGINT $(cat ffmpeg.pid)
        # wait for ffmpeg to exit and finalize the file
        wait $(cat ffmpeg.pid) ||:

    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          selenium-report.html
          video.mp4
          debug_screenshots
