name: End-to-End Tests

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    # Run each browser/os combo in parallel, don't cancel the rest on failure
    strategy:
      fail-fast: false
      matrix:
        include:
          - browser: chrome
            os: ubuntu-latest
          - browser: firefox
            os: ubuntu-latest
          - browser: edge
            os: ubuntu-latest
          # - browser: safari
          #   os: macos-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    env:
      DISPLAY: :99
      RESOLUTION: 1920x1080
      APPDATA: ${{ vars.APPDATA }}
      UNBOUND_EMAIL: ${{ vars.UNBOUND_EMAIL }}
      UNBOUND_EMAIL_PASSWORD: ${{ secrets.UNBOUND_EMAIL_PASSWORD }}
      WONDER_TRADE_WEBHOOK: ${{ secrets.WONDER_TRADE_WEBHOOK }}
      ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      BROWSER: ${{ matrix.browser }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r test-requirements.txt

      - name: Setup Node.js & cache
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'yarn'

      - name: Install JS deps
        run: |
          yarn install
          yarn --cwd server install

      # Only on Linux runners
      - name: Install system deps (Linux only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg

      # Browser installs
      - name: Setup Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: latest
          install-dependencies: true

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Setup Edge
        if: matrix.browser == 'edge'
        uses: browser-actions/setup-edge@v1

      # Safari is built into macOS runners, but WebDriver must be enabled
      - name: Enable Safari WebDriver
        if: matrix.browser == 'safari'
        run: sudo safaridriver --enable # Allow safaridriver to run via WebDriver
        shell: bash  # requires macOS

      - name: Start website & recording
        run: |
          # Start virtual display on Linux
          if [ "${{ runner.os }}" == "Linux" ]; then
            Xvfb ${DISPLAY} -screen 0 ${RESOLUTION}x24 &
          fi

          # Start site and server
          yarn start &
          yarn --cwd server start &
          sleep 5

          # Record the display at 15fps, h264, movflags for faststart
          if [ "${{ runner.os }}" == "Linux" ]; then
            ffmpeg -probesize 10M -y -f x11grab -r 15 -s ${RESOLUTION} -i ${DISPLAY} \
              -c:v libx264 -preset ultrafast -pix_fmt yuv420p \
              -movflags +faststart video-${{ matrix.browser }}.mp4 &
            echo $! > ffmpeg-${{ matrix.browser }}.pid
          fi
        shell: bash

      - name: Run Selenium tests
        run: |
          mkdir -p debug_screenshots_${{ matrix.browser }}
          yarn test-selenium
        timeout-minutes: 5

      - name: Stop recording
        if: always() && runner.os == 'Linux'
        run: |
          # Send Ctrl-C equivalent so ffmpeg writes its trailer
          kill -INT $(cat ffmpeg-${{ matrix.browser }}.pid) || true
          # Wait for ffmpeg to exit and finalize the file
          sleep 2

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.browser }}
          path: |
            selenium-report-${{ matrix.browser }}.html
            video-${{ matrix.browser }}.mp4
            debug_screenshots_${{ matrix.browser }}
