name: End-to-End Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test-requirements.txt

    - name: Start Website
      run: |
        nohup yarn start &
        sleep 10  # Wait for the site to start

    - name: Start server
      run: |
        cd server
        nohup yarn start &
        sleep 10  # Wait for the server to start

    - name: Run Selenium tests
      run: |
        yarn test-selenium
      env:
        APPDATA: ${{ vars.APPDATA }}

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()  # Run this step even if previous steps fail
      with:
        name: selenium-test-results
        path: selenium-report.html
